version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    networks:
      - default
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./data/db:/var/lib/mysql

  form:
    build: ./form
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    networks:
      - web
      - default
    volumes:
      - "./etc/nginx/gateway.conf:/etc/nginx/conf.d/default.conf"
      - "./data/logs/gateway:/var/log/nginx"
    labels:
      traefik.docker.network: "web"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:beeeper.org"
      traefik.basic.port: "80"
      traefik.basic.protocol: "http"
    depends_on:
      - mysqldb

networks:
  web:
    external: true
