version: '3.8'

services:
  mysqldb:
    build:
      dockerfile: ./docker/base/Dockerfile
      context: .    
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - beeeper
    volumes:
      - ./data/db:/var/lib/mysql

  form:
    build: ./form
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
    networks:
      - web
      - beeeper
    labels:
      traefik.docker.network: "web"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:beeeper.org"
      traefik.basic.port: "80"
      traefik.basic.protocol: "http"
    depends_on:
      - mysqldb

networks:
  beeeper:
  web:
    external: true
