version: '3.8'

services:
  gatewayy:
    image: nginx:latest
    ports:
      - 90:80
    networks:
      - web
      - default
    volumes:
      - "./etc/nginx/gateway.conf:/etc/nginx/conf.d/default.conf"
      - "./data/logs/gateway:/var/log/nginx"
    depends_on:
      - page
      - form
    labels:
      traefik.docker.network: "web"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:beeeper.org"
      traefik.basic.port: "80"
      traefik.basic.protocol: "http"

  page:
    image: nginx:latest
    networks:
      - default
    volumes:
      - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./data/logs/page:/var/log/nginx"
      - "./page:/usr/share/nginx/html"
    labels:
      traefik.docker.network: "web"
      traefik.enable: "true"
      traefik.basic.frontend.rule: "Host:bitwarden.lukeurban.tech"
      traefik.basic.port: "80"
      traefik.basic.protocol: "http"

  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - ./data/db:/var/lib/mysql

  form:
    depends_on:
      - mysqldb
    build: ./form
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    networks:
      - default

networks:
  web:
    external: true